FROM python:3.8-buster

RUN apt-get update && apt-get install -y \ 
    curl \
    build-essential \
    unzip \
    libxi6 \
    libgconf-2-4 \
    default-jdk  \
    xvfb

RUN curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
RUN apt-get -y update
RUN apt-get -y install google-chrome-stable


RUN wget https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip
RUN unzip chromedriver_linux64.zip
RUN mv chromedriver /usr/bin/chromedriver
RUN chown root:root /usr/bin/chromedriver
RUN chmod +x /usr/bin/chromedriver

RUN pip install --upgrade pip
                        
WORKDIR /app

ADD requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

EXPOSE 5000